spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'

office:
  seating:
    #First Office
    1: 'DANIEL BROITZMANN'
    2: 'TORBEN SÜFKE'
    3: 'FREI'
    4: 'FREI'
    #Second Office
    5: 'FREI'
    6: 'SELIM UFAKACAR'
    7: 'FREI'
    8: 'THORBEN SCHILLER'
    #Third Office
    9: 'JOSEPHINE MORITZ'
    10: 'EGOR FABRICIUS'
    11: 'MARIUS SONTOPSKI'
    12: 'YVONNE WEDEMEIER'
    13: 'FRANTZ TCHAMBO'
    14: 'RUBEN SCHMIDT'
    15: 'KARINA KNOLL'
    16: 'CHRISTIAN TIEDT'
    17: 'NATALI KÄFER'
    18: 'LENA KÖHLER'
    19: 'LENA ROSENBOOM'
    20: 'PHILIPP SAHNER'
    #Fourth Office
    21: 'CHRISTIAN KOHL'
    22: 'CORNELIA HERING'