spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'

office1:
  desk01: 'Daniel Broitzmann'
  desk02: 'Torben Süfke'
  desk03: 'leer'
  desk04: 'leer'

office2:
  desk01: 'leer'
  desk02: 'Selim Ufakacar'
  desk03: 'leer'
  desk04: 'Thorben Schiller'

office3:
  desk01: 'Josephine Moritz'
  desk02: 'Egor Fabricius'
  desk03: 'Marius Sontopski'
  desk04: 'Yvonne Wedemeier'
  desk05: 'Frantz Tchambo'
  desk06: 'Ruben Smidt'
  desk07: 'Karina Knoll'
  desk08: 'Christian Tiedt'
  desk09: 'Natali Käfer'
  desk10: 'Lena Köhler'
  desk11: 'Lena Rosenboom'
  desk12: 'Philipp Sahner'

office4:
  desk01: 'Christian Kohl'
  desk02: 'Cornelia Hering'