spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'

office:
  seating:
    #First Office
    1: 'Daniel Broitzmann'
    2: 'Torben Süfke'
    3: 'frei'
    4: 'frei'
    #Second Office
    5: 'frei'
    6: 'Selim Ufakacar'
    7: 'frei'
    8: 'Thorben Schiller'
    #Third Office
    9: 'Josephine Moritz'
    10: 'Egor Fabricius'
    11: 'Marius Sontopski'
    12: 'Yvonne Wedemeier'
    13: 'Frantz Tchambo'
    14: 'Ruben Smidt'
    15: 'Karina Knoll'
    16: 'Christian Tiedt'
    17: 'Natali Käfer'
    18: 'Lena Köhler'
    19: 'Lena Rosenboom'
    20: 'Philipp Sahner'
    #Fourth Office
    21: 'Christian Kohl'
    22: 'Cornelia Hering'